env:
  global:
  - secure: ZiFoh4hahmVqFepJg3pTEwcK2wxWnQO9Vyr4g2xYjd6PAUv6ehUvA5sJXgf3k68Pkc8adnyjQwhNNdEzkLGujzdF9wMCLg0tyeyjmRe+ZDkV2k5icvz+P2JxCv/CtCDRQ/yLUZ6xWOF2cZ/IfaYvd4o7LZYYXzbRa8VupGUQLHk8i5zgl2xY2k1czTwP63SzeT8FXIFmduekZ7eFCJ8/Yi3HGhNCsWibHCIhypyjtQrPZkpzmyUEwuKe/HUuCLzKNfOCgiG08dJboPlkdUDpjEVAFvEg4rcwAcoKiZlhAdaZn8ZoLUv/SZfSley+lgUONifpvUf5P+M7ay6iwX4BBa263M56t0443iDqzJfF0s0JcgIoquebBTHTWG/5ilB/82kTK5KAnFaqwUVMZZVWdiYPpFC9Olvbhh75a8VJ0OnW3PnghTOdnHQfEP7Wg4Jvwke6zK70GdiA3rjyeV4VMBuUVFb24xvXiL1fpqV97eDeZpD0ySQiKBB7urgKQ6e3oIqz06GDJu5W09YzHpezPyQSiLtLd34KyvUgRsozOPGAUKNS2Q1mRleWGfVCRPeui5fgfaGtT+m7Q8ZiABhNaaWvGz8NNGRN/qFGU02sytJGX6is8altRDf5pwMEDdRXjWyNq0kvJZjCU/oZ8zc46f9tCXVOK2daRXJkEdbnGS4=
  - secure: V0kWnRFjbDW40w/K4UHsW0H/bI5yVpMurdZ3lHSGrfiuOg/9RoURAO3lnp6A8m0F+Hu6oVdOFy9ZB+GOBXuObjuDdpWHzRms37I/5cJHdFJWXGaYI4q9GiabJtHiADfAqDrcCNabRPezvcmv2353vwp68l8mwnFnHZYyFboThToqFXdvxXikqp3DjVYlHcsHYUW9gpc/GOE0OAokSEAAHT3YJ35492plfrnbKGxYP/lNNTJi0MVS3V4NFvhs8NNb/O5LopEm5Et1uBHRhuUgThweS52SSmksET+A2FD64y7RS8Ph4MdYKdHjg5vERznEhIuj5wnXUEWQqPegZmwmUlJ13koWDIYxFItYSwAoYpAsJj1qYuim2R6wQKfstR4TJBq+MZ9NG5e9QIQr5lcaaz1RIscd33MTIbK5e5nNKuFGjXfYo1W8DZw1uRdhnsmFeXQ0vhgZceYl7zCHrArdh0TtH+vL8/Is8aWiCkMciDvegUhyw/Y1U1yBohZ7yHeGNu+rgN7U+Q/xn1pgwCFvUftOVgOqePrKYLVktT0Q2SlsT9sEztO2wJTpxGOonOu2CGfbZk0gLPkJBpBzzJAtYftgUeKp85qR4ollE1CUq89zmnnkKCiS4FozgJeJ7cNUkB3caxxXD4DP3Sp7IDVI7pJkoDz2VjV+++hS9Kwfjec=

jobs:
  include:
  - language: go
    go: 1.10.x
    node_js: lts/*

    cache:
      directories:
      - vendor

    before_script:
    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    - go get -u github.com/go-bindata/go-bindata/...

    install:
    - # skip

    script:
    - make

    deploy:
    - provider: script
      script: curl -T "go-wiki" -u "$BINTRAY_USER:$BINTRAY_API_KEY" -H "X-Bintray-Publish:1" -H "X-Bintray-Package:linux" -H "X-Bintray-Version:latest-$(date +%Y-%m-%d)" -H "X-Bintray-Override:1" "https://api.bintray.com/content/rootlogin/go-wiki/latest-$(date +%Y-%m-%d)/go-wiki"
      skip_cleanup: true
      on:
        branch: master

    - provider: script
      script: curl -T "go-wiki" -u "$BINTRAY_USER:$BINTRAY_API_KEY" -H "X-Bintray-Publish:1" -H "X-Bintray-Package:linux" -H "X-Bintray-Version:$TRAVIS_TAG" -H "X-Bintray-Override:1" "https://api.bintray.com/content/rootlogin/go-wiki/$TRAVIS_TAG/go-wiki"
      skip_cleanup: true
      on:
        tags: true