[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.5.0"

[[constraint]]
  name = "github.com/russross/blackfriday"
  version = "2.0.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "github.com/badoux/checkmail"
  branch = "master"

[[constraint]]
  name = "github.com/microcosm-cc/bluemonday"
  branch = "master"

[[constraint]]
  name = "gopkg.in/dgrijalva/jwt-go.v3"
  version = "3.2.0"

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "0.3.6"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "2.1.0"

[[constraint]]
  name = "github.com/chrootlogin/event"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-plugin"

[[constraint]]
  branch = "master"
  name = "github.com/chrootlogin/go-wiki-plugin-sdk"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"
